lbs:
  source:
    # according to https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/install.md/#installing-secp256k1
    # using https://github.com/bitcoin-core/secp256k1/commit/ac83be33
    download: 
      "secp256k1-cardano.tar.gz": "https://github.com/bitcoin-core/secp256k1/archive/ac83be33d0956faf6b7f61a60ab524ef7d6a473a.tar.gz"
